export type Donation = {
  id: string;
  title: string;
  description: string;
  quantity: string;
  category: 'FOOD' | 'CLOTHES' | 'BOOKS';
  itemType: string;
  expiresAt: string | null;
  status: 'AVAILABLE' | 'CLAIMED' | 'COLLECTED';
  address: string;
  city: string;
  donorName: string;
  donorType: string;
  postedAgo: string;
};

export const DONATIONS: Donation[] = [
  {
    id: '1',
    title: 'Fresh Vegetable Bundle',
    description: 'Assorted seasonal vegetables from our terrace garden – tomatoes, brinjals, curry leaves.',
    quantity: '5 kg',
    category: 'FOOD',
    itemType: 'Vegetables',
    expiresAt: 'Expires in 2 days',
    status: 'AVAILABLE',
    address: '12 Anna Nagar',
    city: 'Chennai',
    donorName: 'Priya Rajan',
    donorType: 'Individual',
    postedAgo: '2 hours ago',
  },
  {
    id: '2',
    title: 'Cooked Biryani – 30 Portions',
    description: 'Event leftovers from a wedding function. Freshly cooked, packed hygienically.',
    quantity: '30 portions',
    category: 'FOOD',
    itemType: 'Cooked Food',
    expiresAt: 'Expires in 6 hours',
    status: 'AVAILABLE',
    address: '45 T Nagar',
    city: 'Chennai',
    donorName: 'Star Catering Co.',
    donorType: 'Business',
    postedAgo: '1 hour ago',
  },
  {
    id: '3',
    title: 'Basmati Rice – 10 kg',
    description: 'Unopened pack of premium basmati rice, purchased in bulk.',
    quantity: '10 kg',
    category: 'FOOD',
    itemType: 'Grains & Pulses',
    expiresAt: 'Best before: Dec 2025',
    status: 'CLAIMED',
    address: '22 Velachery',
    city: 'Chennai',
    donorName: 'Ramesh Kumar',
    donorType: 'Individual',
    postedAgo: '1 day ago',
  },
  {
    id: '4',
    title: 'Men\'s Winter Jackets',
    description: 'Gently used warm jackets, sizes M to XL. Washed and ready for pickup.',
    quantity: '8 pieces',
    category: 'CLOTHES',
    itemType: 'Winter Wear',
    expiresAt: null,
    status: 'AVAILABLE',
    address: '78 Adyar',
    city: 'Chennai',
    donorName: 'Meena Sundar',
    donorType: 'Individual',
    postedAgo: '3 hours ago',
  },
  {
    id: '5',
    title: "Children's School Uniforms",
    description: 'Clean school uniforms for kids aged 6–12. Includes shirts, pants, and frocks.',
    quantity: '15 sets',
    category: 'CLOTHES',
    itemType: "Children's Wear",
    expiresAt: null,
    status: 'AVAILABLE',
    address: '9 Mylapore',
    city: 'Chennai',
    donorName: 'Helping Hand Trust',
    donorType: 'NGO',
    postedAgo: '5 hours ago',
  },
  {
    id: '6',
    title: "Women's Sarees & Salwars",
    description: 'Traditional sarees and salwar sets, good condition, various sizes.',
    quantity: '20 pieces',
    category: 'CLOTHES',
    itemType: "Women's Wear",
    expiresAt: null,
    status: 'COLLECTED',
    address: '5 Nungambakkam',
    city: 'Chennai',
    donorName: 'Anitha Krishnan',
    donorType: 'Individual',
    postedAgo: '2 days ago',
  },
  {
    id: '7',
    title: 'CBSE Textbooks – Class 6 to 10',
    description: 'Lightly used CBSE textbooks covering all subjects. Great condition.',
    quantity: '30 books',
    category: 'BOOKS',
    itemType: 'Textbooks',
    expiresAt: null,
    status: 'AVAILABLE',
    address: '18 Kilpauk',
    city: 'Chennai',
    donorName: 'Suresh Babu',
    donorType: 'Individual',
    postedAgo: '4 hours ago',
  },
  {
    id: '8',
    title: 'English Story Books – All Ages',
    description: 'Collection of 15 novels and storybooks ranging from children to adult fiction.',
    quantity: '15 books',
    category: 'BOOKS',
    itemType: 'Story Books',
    expiresAt: null,
    status: 'AVAILABLE',
    address: '33 Besant Nagar',
    city: 'Chennai',
    donorName: 'Lakshmi Priya',
    donorType: 'Individual',
    postedAgo: '6 hours ago',
  },
  {
    id: '9',
    title: 'Competitive Exam Books – UPSC/TNPSC',
    description: 'Reference books and previous year question papers for government exams.',
    quantity: '12 books',
    category: 'BOOKS',
    itemType: 'Reference Books',
    expiresAt: null,
    status: 'CLAIMED',
    address: '67 Tambaram',
    city: 'Chennai',
    donorName: 'Vijay Mohan',
    donorType: 'Individual',
    postedAgo: '1 day ago',
  },
  {
    id: '10',
    title: 'Surplus Fruits – Mangoes & Bananas',
    description: 'Fresh mangoes and bananas from our farm. Perfectly ripe, collected this morning.',
    quantity: '8 kg',
    category: 'FOOD',
    itemType: 'Fruits',
    expiresAt: 'Expires in 3 days',
    status: 'AVAILABLE',
    address: '10 Chromepet',
    city: 'Chennai',
    donorName: 'Green Farms',
    donorType: 'Business',
    postedAgo: '30 minutes ago',
  },
  {
    id: '11',
    title: 'Footwear – Mixed Sizes',
    description: 'Assorted sandals and shoes in good condition, sizes 4–10.',
    quantity: '25 pairs',
    category: 'CLOTHES',
    itemType: 'Footwear',
    expiresAt: null,
    status: 'AVAILABLE',
    address: '14 Porur',
    city: 'Chennai',
    donorName: 'Kavitha Nair',
    donorType: 'Individual',
    postedAgo: '1 day ago',
  },
  {
    id: '12',
    title: 'Children\'s Activity Books',
    description: 'Coloring books, activity pads, and learning workbooks for ages 3–8.',
    quantity: '20 books',
    category: 'BOOKS',
    itemType: 'Children Books',
    expiresAt: null,
    status: 'AVAILABLE',
    address: '55 Anna Nagar West',
    city: 'Chennai',
    donorName: 'Bright Minds School',
    donorType: 'Institution',
    postedAgo: '2 days ago',
  },
];

export const STATS = {
  totalDonations: 248,
  activeDonations: 87,
  ngoPartners: 34,
  citiesCovered: 12,
  livesImpacted: 1820,
};

export const CATEGORY_META = {
  FOOD:    { emoji: '🍱', label: 'Food',    color: 'bg-orange-100 text-orange-700', count: 34 },
  CLOTHES: { emoji: '👕', label: 'Clothes', color: 'bg-blue-100 text-blue-700',   count: 28 },
  BOOKS:   { emoji: '📚', label: 'Books',   color: 'bg-purple-100 text-purple-700', count: 25 },
} as const;

export const STATUS_META = {
  AVAILABLE: { label: 'Available', color: 'bg-green-100 text-green-800' },
  CLAIMED:   { label: 'Claimed',   color: 'bg-yellow-100 text-yellow-800' },
  COLLECTED: { label: 'Collected', color: 'bg-blue-100 text-blue-800' },
};
